# Generated by Django 4.2.5 on 2023-09-27 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=100)),
                ('subject_workload', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=50)),
                ('user_birthdate', models.DateField(null=True)),
                ('user_type', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_description', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserAndSubject',
            fields=[
                ('relation_id', models.AutoField(primary_key=True, serialize=False)),
                ('relation_grade', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('subject_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deloitteapp.subject')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deloitteapp.users')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deloitteapp.users'),
        ),
    ]
