# Generated by Django 4.2.5 on 2023-10-01 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deloitteapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='teacher_name',
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='deloitteapp.teacher'),
        ),
    ]
