# Generated by Django 4.2.5 on 2023-09-27 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deloitteapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userandsubject',
            old_name='relation_grade',
            new_name='user_subject_grade',
        ),
        migrations.RenameField(
            model_name='userandsubject',
            old_name='relation_id',
            new_name='user_subject_id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_type',
        ),
        migrations.AddField(
            model_name='users',
            name='type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deloitteapp.usertype'),
        ),
    ]
