# Generated by Django 4.2.5 on 2023-09-30 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deloitteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
