# Generated by Django 4.2.5 on 2023-09-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deloitteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='', max_length=255),
        ),
    ]
