# Generated by Django 4.2.5 on 2023-10-01 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deloitteapp', '0002_remove_subject_teacher_name_subject_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='teacher',
            new_name='teacher_name',
        ),
    ]
